### ISSUE TITLE
关于luci-app-autoupdate使用问题

### ISSUE THREAD

**Issue by ilxp** [Hyy2001X/AutoBuild-Packages#19]
感谢大佬的在线升级贡献。今天试了下，有几个问题请教下。
1、app反应慢。
2、github地址：是填写https://github.com/Hyy2001X/AutoBuild-Actions-BETA   还是 https://github.com/Hyy2001X/AutoBuild-Actions-BETA/releases/tag/AutoUpdate ？

3、固件标签：  是填写[ ](https://github.com/Hyy2001X/AutoBuild-Actions-BETA/releases/tag/AutoUpdate)下的 AutoBuild-lede-x86_64-R23.11.11-20240102-UEFI-Full-5f402.img.gz  这个地址的哪一个呢？

4、是不是生成的固件名称格式必须为：AutoBuild-lede-x86_64-R23.11.11-20240102-UEFI-Full-5f402.img.gz  这样的吗？

5、Log Path  ：随便是顶一个临时目录：/tmp  ?

我编译好了ipk，供测试：
https://github.com/ilxp/luci-app-autoupdate-Hyy2001X/releases/tag/oprx-oR

**Comment by Hyy2001X** [comment]
luci-app-autoupdate 这个包必须搭配[在线编译](https://github.com/Hyy2001X/AutoBuild-Actions-BETA)去使用，环境会给你自动配置好，单独编译是没用的。
1.app反应慢是网络问题，最好使用透明代理
2.github地址https://github.com/Hyy2001X/AutoBuild-Actions-BETA，用在线编译的固件会给你自动配置好
3.4.5.同理2

**Comment by ilxp** [comment]
明白了。自己多研究下：
1、app反应慢。在lean的lede上不存在反应慢。官方openwrt23.05上慢。
2、github地址：是写https://github.com/Hyy2001X/AutoBuild-Actions-BETA  即为自动编译项目地址。

3、固件标签： 是填写 下的 AutoBuild-lede-x86_64-R23.11.11-20240102-UEFI-Full-5f402.img.gz 这个地址的Full。

5、Log Path ：随便是顶一个临时目录：/tmp
