### ISSUE TITLE
AdguardHome Luci 默认更新为beta版的问题

### ISSUE THREAD

**Issue by chermy** [Hyy2001X/AutoBuild-Packages#8]
AutoBuild-Packages/luci-app-adguardhome/root/usr/share/AdGuardHome/update_core.sh
[https://github.com/Hyy2001X/AutoBuild-Packages/blob/master/luci-app-adguardhome/root/usr/share/AdGuardHome/update_core.sh#L38](https://github.com/Hyy2001X/AutoBuild-Packages/blob/master/luci-app-adguardhome/root/usr/share/AdGuardHome/update_core.sh#L38)
检测地址应为: [https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest](https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest)

上游目前也已经是latest: [https://github.com/rufengsuixing/luci-app-adguardhome/blob/master/root/usr/share/AdGuardHome/update_core.sh](https://github.com/rufengsuixing/luci-app-adguardhome/blob/master/root/usr/share/AdGuardHome/update_core.sh)
如果不加latest则会检测第一次出现tag_name的版本, 包括beta版本.

**Comment by Hyy2001X** [comment]
感谢反馈 加了一个选项，现在可以手动选择 beta版本或者 latest版本
